services:
  - type: web
    name: huly-nginx
    runtime: image
    image:
      url: docker.io/library/nginx:1.21.3
    plan: free
    envVars:
      - key: HTTP_BIND
        value: 0.0.0.0
      - key: HTTP_PORT
        value: 80

  - type: web
    name: huly-minio
    healthCheckPath: /minio/health/live
    runtime: image
    image:
      url: docker.io/minio/minio:latest
    dockerCommand: minio server /data --address $HOST:$PORT
    autoDeploy: false
    disk:
      name: data
      mountPath: /data
    envVars:
    - key: MINIO_ROOT_USER
      generateValue: true
    - key: MINIO_ROOT_PASSWORD
      generateValue: true
    - key: HOST
      value: "0.0.0.0"
    - key: PORT
      value: 9000
    - key: CONSOLE_PORT
      value: 9090
    - key: MINIO_BROWSER
      value: "off"

  - type: web
    name: huly-elastic
    runtime: image
    image:
      url: docker.io/library/elasticsearch:7.14.2
    plan: standard
    envVars:
      - key: ELASTICSEARCH_PORT_NUMBER
        value: "9200"
      - key: BITNAMI_DEBUG
        value: "true"
      - key: discovery.type
        value: "single-node"
      - key: ES_JAVA_OPTS
        value: "-Xms1024m -Xmx1024m"
      - key: http.cors.enabled
        value: "true"
      - key: http.cors.allow-origin
        value: "http://localhost:8082"

  - type: web
    name: huly-front
    runtime: image
    image:
      url: docker.io/hardcoreeng/front:v0.6.501
    plan: free
    envVars:
      - key: SERVER_PORT
        value: 80
      - key: SERVER_SECRET
        sync: false
      - key: ACCOUNTS_URL
        value: https://huly-account.onrender.com
      - key: REKONI_URL
        value: https://huly-rekoni.onrender.com
      - key: STATS_URL
        value: https://huly-stats.onrender.com
      - key: UPLOAD_URL
        value: /files
      - key: COLLABORATOR_URL
        value: wss://huly-collaborator.onrender.com
      - key: TITLE
        value: Huly Self Host
      - key: DEFAULT_LANGUAGE
        value: en
      - key: LAST_NAME_FIRST
        value: "false"
      - key: DESKTOP_UPDATES_CHANNEL
        value: selfhost
      - key: LIVEKIT_WS
        sync: false
      - key: LOVE_ENDPOINT
        value: https://huly-love.onrender.com
      - key: AI_URL
        value: https://huly-aibot.onrender.com
      - key: GMAIL_URL
        value: https://huly-front.onrender.com/_gmail
      - key: CALENDAR_URL
        value: https://huly-front.onrender.com/_calendar
      - key: TELEGRAM_URL
        value: https://huly-front.onrender.com/_telegram
      - key: ELASTIC_URL
        value: https://huly-elastic.onrender.com
      - key: STORAGE_CONFIG
        value: minio|minio?accessKey=minioadmin&secretKey=minioadmin
      - key: DB_URL
        sync: false
      - key: MONGO_URL
        sync: false
      - key: PUSH_PUBLIC_KEY
        value: BCS4xddQoWP9F74HmidSEsSJ4Tn7d0cbk8q9sgtNTpDsQmtMMLIqF
      - key: PUSH_PRIVATE_KEY
        value: X8xQIr3ZmjJCPDeZ6ScrXkT54qJx5tqZnZzXwVog07A

  - type: web
    name: huly-account
    runtime: image
    image:
      url: docker.io/hardcoreeng/account:v0.6.501
    plan: free
    envVars:
      - key: SERVER_PORT
        value: 3000
      - key: SERVER_SECRET
        sync: false
      - key: DB_URL
        sync: false
      - key: MONGO_URL
        sync: false
      - key: TRANSACTOR_URL
        value: wss://huly-transactor.onrender.com
      - key: STORAGE_CONFIG
        sync: false
      - key: FRONT_URL
        value: https://huly-front.onrender.com
      - key: STATS_URL
        value: https://huly-stats.onrender.com
      - key: MODEL_ENABLED
        value: "*"
      - key: MAIL_URL
        value: https://huly-mail.onrender.com

  - type: web
    name: huly-transactor
    runtime: image
    image:
      url: docker.io/hardcoreeng/transactor:v0.6.501
    plan: free
    envVars:
      - key: SERVER_PORT
        value: 3333
      - key: SERVER_SECRET
        sync: false
      - key: DB_URL
        sync: false
      - key: MONGO_URL
        sync: false
      - key: STORAGE_CONFIG
        sync: false
      - key: FRONT_URL
        value: https://huly-front.onrender.com
      - key: ACCOUNTS_URL
        value: https://huly-account.onrender.com
      - key: FULLTEXT_URL
        value: https://huly-fulltext.onrender.com
      - key: STATS_URL
        value: https://huly-stats.onrender.com
      - key: MAIL_URL
        value: https://huly-mail.onrender.com
      - key: AI_BOT_URL
        value: https://huly-aibot.onrender.com

  - type: web
    name: huly-collaborator
    runtime: image
    image:
      url: docker.io/hardcoreeng/collaborator:v0.6.501
    plan: free
    envVars:
      - key: COLLABORATOR_PORT
        value: 3078
      - key: SECRET
        sync: false
      - key: ACCOUNTS_URL
        value: https://huly-account.onrender.com
      - key: DB_URL
        sync: false
      - key: STATS_URL
        value: https://huly-stats.onrender.com
      - key: STORAGE_CONFIG
        sync: false

  - type: web
    name: huly-stats
    runtime: image
    image:
      url: docker.io/hardcoreeng/stats:v0.6.501
    plan: free
    envVars:
      - key: PORT
        value: 4900
      - key: SERVER_SECRET
        sync: false

  - type: web
    name: huly-fulltext
    runtime: image
    image:
      url: docker.io/hardcoreeng/fulltext:v0.6.501
    plan: free
    envVars:
      - key: SERVER_SECRET
        sync: false
      - key: DB_URL
        sync: false
      - key: FULLTEXT_DB_URL
        sync: false
      - key: ELASTIC_INDEX_NAME
        value: huly_storage_index
      - key: STORAGE_CONFIG
        sync: false
      - key: REKONI_URL
        value: https://huly-rekoni.onrender.com
      - key: ACCOUNTS_URL
        value: https://huly-account.onrender.com
      - key: STATS_URL
        value: https://huly-stats.onrender.com

  - type: web
    name: huly-rekoni
    runtime: image
    image:
      url: docker.io/hardcoreeng/rekoni-service:v0.6.501
    plan: free
    envVars:
      - key: SECRET
        sync: false

  - type: web
    name: huly-mail
    runtime: image
    image:
      url: docker.io/hardcoreeng/mail:v0.6.501
    plan: free
    envVars:
      - key: PORT
        value: 8097
      - key: SOURCE
        sync: false
      - key: SES_ACCESS_KEY
        sync: false
      - key: SES_SECRET_KEY
        sync: false
      - key: SES_REGION
        sync: false

  - type: web
    name: huly-workspace
    runtime: image
    image:
      url: docker.io/hardcoreeng/workspace:v0.6.501
    plan: free
    envVars:
      - key: SERVER_SECRET
        sync: false
      - key: DB_URL
        sync: false
      - key: MONGO_URL
        sync: false
      - key: TRANSACTOR_URL
        value: wss://huly-transactor.onrender.com
      - key: STORAGE_CONFIG
        sync: false
      - key: MODEL_ENABLED
        value: "*"
      - key: ACCOUNTS_URL
        value: https://huly-account.onrender.com
      - key: STATS_URL
        value: https://huly-stats.onrender.com
      - key: PORT
        value: "3001"
      - key: HOST
        value: "0.0.0.0"

  - type: web
    name: huly-love
    runtime: image
    image:
      url: docker.io/hardcoreeng/love:v0.6.501
    plan: free
    envVars:
      - key: STORAGE_CONFIG
        sync: false
      - key: SECRET
        sync: false
      - key: ACCOUNTS_URL
        value: https://huly-account.onrender.com
      - key: DB_URL
        sync: false
      - key: MONGO_URL
        sync: false
      - key: STORAGE_PROVIDER_NAME
        value: minio
      - key: PORT
        value: 8096
      - key: LIVEKIT_HOST
        sync: false
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_API_SECRET
        sync: false


  - type: web
    name: huly-aibot
    runtime: image
    image:
      url: docker.io/hardcoreeng/ai-bot:v0.6.501
    plan: free
    envVars:
      - key: STORAGE_CONFIG
        sync: false
      - key: SERVER_SECRET
        sync: false
      - key: ACCOUNTS_URL
        value: https://huly-account.onrender.com
      - key: DB_URL
        sync: false
      - key: MONGO_URL
        sync: false
      - key: STATS_URL
        value: https://huly-stats.onrender.com
      - key: FIRST_NAME
        value: Bot
      - key: LAST_NAME
        value: Huly AI
      - key: PASSWORD
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_BASE_URL
        sync: false
      - key: LOVE_ENDPOINT
        value: https://huly-love.onrender.com 